version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: "dcim_app"
    ports:
      - "5005:5050"
    depends_on:
      - db
    networks:
      - test

  db:
    container_name: "postgres_db"
    image: postgres:latest
    env_file:
      - .env
    restart: always
    networks:
      - test


networks:
  test:
    driver: bridge